# Generated by Django 5.1.6 on 2025-02-28 21:58

import bizlaunch.funnels.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('client_data', models.JSONField(help_text='Client input data for copy generation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('client_file', models.FileField(blank=True, help_text='Any supporting file from client', null=True, upload_to=bizlaunch.funnels.models.copy_job_file_upload_path)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_jobs', to='funnels.systemtemplate')),
                ('user', models.ForeignKey(help_text='User initiating the job', on_delete=django.db.models.deletion.CASCADE, related_name='copy_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdCopy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('copy_text', models.TextField(help_text='Generated ad copy text')),
                ('copy_json', models.JSONField(default=dict, help_text='Generated ad copy in JSON format')),
                ('funnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.funneltemplate')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnels.pagetemplate')),
                ('copy_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_copies', to='funnels.copyjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
