# Generated by Django 5.1.6 on 2025-02-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_copyjob_adcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='image_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
