# Generated by Django 5.1.6 on 2025-03-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0003_alter_pageimage_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
