# Generated by Django 5.1.6 on 2025-04-08 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0005_copyjob_celery_task_id_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcopy',
            name='page',
        ),
        migrations.AlterField(
            model_name='adcopy',
            name='funnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_copies', to='funnels.funneltemplate'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image_content',
            field=models.TextField(blank=True, help_text='Base64-encoded string of the image content.', null=True),
        ),
    ]
